/* All business text is rendered with textContent. Approval stays server-side. */
'use strict';
const $ = id => document.getElementById(id);
const FONT_KEY = 'sweaterco.text-size';
function setTextSize(size){const value=['small','medium','large'].includes(size)?size:'medium';document.documentElement.dataset.textSize=value;document.querySelectorAll('[data-text-size]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.textSize===value)));try{localStorage.setItem(FONT_KEY,value);}catch{}return value;}
function initTextSize(){let saved='medium';try{saved=localStorage.getItem(FONT_KEY)||saved;}catch{}setTextSize(saved);document.querySelectorAll('[data-text-size]').forEach(b=>b.addEventListener('click',()=>setTextSize(b.dataset.textSize)));}
const state = {user:null, desk:null, session:null, pending:null, busy:false, page:1, inboxLimit:10, order:null, event:null};
const objectives = {min_delay:'Fastest completion', min_cost:'Lowest cost', min_defects:'Lowest defects', hybrid:'Time & quality balance'};
const labels = {PENDING:'Pending', CLARIFY:'Needs clarification', ACTIVE:'Ready for review', AWAITING_CLARIFICATION:'Needs clarification', CLOSED:'Closed', ALLOCATE:'Allocated', REVIEW:'Review', ACTIVE_WORKSHOP:'Active', WORKING:'In production', READY:'Ready', UNASSIGNED:'Unassigned', COMPLETED:'Completed', LAPSED:'Lapsed', REFUSE:'Refused', ESCALATE:'Escalated', ERROR:'Error', SUSPENDED:'Suspended', REASSIGNED:'Reassigned'};
const reasonLabels = {closed:'Workshop is closed', inactive:'Workshop is inactive', excluded:'Excluded by request', category_mismatch:'Category not supported', unsupported_category:'Category not supported', batch_limit:'Batch limit exceeded', max_batch_exceeded:'Batch limit exceeded', ELIGIBLE:'Eligibility checks passed', BEST_CONFIGURED_SCORE:'Best score for the configured objective', INTEGER_PIECES_CONSERVED:'All remaining pieces are allocated', ESTIMATED_DEADLINE_MISS:'Estimated completion is after the order due date.', RECOMMENDATION_REJECTED:'Recommendation rejected. Enter a revised request.', order_id:'Order ID is missing', UNSUPPORTED_REPLY:'This update is not supported. Use a complete replacement request.', ORDER_VERSION_CONFLICT:'The order changed. Revise the request to review its latest state.', PARSER_ERROR:'The parser could not complete the request. Please retry or replace the request.', NO_ELIGIBLE_WORKSHOP:'No eligible workshop is available.', DEADLINE_INFEASIBLE:'No allocation meets the required deadline.', CAPACITY_INFEASIBLE:'No allocation fits the batch and workshop count limits.'};
const pretty = s => reasonLabels[s] || String(s || '').replaceAll('_',' ').toLowerCase();
const num = (n,d=2) => typeof n === 'number' ? n.toLocaleString('en-SG',{maximumFractionDigits:d}) : '—';
const stamp = s => s ? new Date(s).toLocaleString('en-SG',{dateStyle:'medium',timeStyle:'short'}) : '—';
const el = (tag,text,cls) => {const n=document.createElement(tag);if(text!==undefined&&text!==null)n.textContent=text;if(cls)n.className=cls;return n;};
function tag(value,label) {const good=['ALLOCATE','WORKING','COMPLETED','ACTIVE','REVIEW'].includes(value);const bad=['CLOSED','LAPSED','ERROR','REFUSE','SUSPENDED'].includes(value);return el('span',label||labels[value]||pretty(value),'tag '+(good?'good':bad?'bad':'warn'));}
function action(text,fn,mutate=false){const n=el('button',text,'quiet');n.type='button';if(mutate)n.dataset.mutate='';n.addEventListener('click',()=>Promise.resolve(fn()).catch(report));return n;}
function table(target,headers,rows,empty='No records to display.'){target.replaceChildren();if(!rows.length){target.append(el('p',empty,'empty'));return;}const t=el('table'),head=t.createTHead().insertRow();headers.forEach(h=>head.append(el('th',h)));const body=t.createTBody();rows.forEach(row=>{const tr=body.insertRow();row.forEach(v=>{const td=tr.insertCell();if(v instanceof Node)td.append(v);else td.textContent=v??'—';});});target.append(t);}
function pair(primary,secondary){const n=el('div');n.append(el('strong',primary||'—'));if(secondary)n.append(el('small',secondary));return n;}
function facts(target,values){const dl=el('dl',null,'key-values');values.forEach(([k,v])=>{const p=el('div');p.append(el('dt',k),el('dd',v??'—'));dl.append(p);});target.replaceChildren(dl);}
function notify(text,error=false){$('feedback').hidden=!text;$('feedback').textContent=text||'';$('feedback').classList.toggle('error',error);}
function report(error){notify(error.message||'The operation could not be completed.',true);}
function storageKey(){return 'sweaterco.desk.v1.'+(state.user?.username||'');}
function persist(){try{localStorage.setItem(storageKey(),JSON.stringify({id:state.session?.session_id||state.savedId,pending:state.pending}));}catch{notify('Browser storage is unavailable. Keep this tab open until the operation finishes.',true);}}
async function api(url,options){const response=await fetch(url,options);let data;try{data=await response.json();}catch{throw Error('The server returned an unreadable response.');}if(response.status===401){if(data.error==='LOGIN_REQUIRED')showLogin();throw Error(data.error==='INVALID_CREDENTIALS'?'Incorrect username or password.':'Please sign in to continue.');}if(!response.ok)throw Error(data.message||data.error||data.result?.message||'Request failed.');return data;}
function canAccept(){return state.session?.state==='ACTIVE'&&!state.session.blockers.length&&state.session.last_response?.result?.success&&state.session.last_response?.result?.decision_status==='REVIEW';}
function controls(){document.querySelectorAll('[data-mutate]').forEach(n=>n.disabled=state.busy||!!state.pending);const closed=!state.session||state.session.state==='CLOSED';['send','replace','close-session','edit-request','apply-details','details-fields'].forEach(id=>$(id).disabled=state.busy||!!state.pending||closed);['accept','decision-accept','reject'].forEach(id=>$(id).disabled=state.busy||!!state.pending||!canAccept());$('message').disabled=closed||state.busy||!!state.pending;$('objective').disabled=closed||state.busy||!!state.pending;$('pending-banner').hidden=!state.pending;$('retry').disabled=state.busy;$('logout').disabled=state.busy||!!state.pending;$('request-editor').hidden=closed;}
function showLogin(){document.querySelectorAll('dialog[open]').forEach(d=>d.close());$('app').hidden=true;$('login-screen').hidden=false;$('password').value='';}
async function boot(){const me=await api('/api/auth/me');state.session=null;state.order=null;state.user=me;$('setup-help').hidden=!me.setup_required;if(!me.username){showLogin();return;}$('login-screen').hidden=true;$('app').hidden=false;$('account-name').textContent=me.auth_required?me.username:'Local demo · no login';$('logout').hidden=!me.auth_required;let saved={};try{saved=JSON.parse(localStorage.getItem(storageKey())||'{}');}catch{}state.pending=saved.pending||null;state.savedId=saved.id;const health=await api('/api/health');state.backend=health.backend;$('backend').textContent={offline:'Offline rules',llm:'Gemini',deepseek:'DeepSeek'}[health.backend]||health.backend;$('release').textContent=health.version;const ai=await api('/api/ai/status');$('ai-status').textContent=health.backend==='offline'?'Offline mode · Use the details form or short updates such as “cheapest” and “exclude W3”. Configure DeepSeek on the server to enable AI text processing.':ai.configured?`${$('backend').textContent} · ${ai.model} · Configured for new requests. The connection is checked when you send a request.`:`${$('backend').textContent} needs a local API key. You can still use Edit details.`;await refreshDesk();if(saved.id){try{await loadSession(saved.id,false);}catch{notify('The last request could not be restored. Select a request from the queue.',true);}}renderSession();controls();await route();}
async function refreshDesk(){state.desk=await api('/api/dashboard');renderHome();renderQueue();$('recommendation-counts').textContent=`Pending: ${state.desk.stats.pending}   ·   Needs clarification: ${state.desk.stats.clarification}   ·   In production: ${state.desk.stats.assigned}`;$('order-options').replaceChildren(...state.desk.orders.map(o=>{const n=el('option');n.value=o.order_id;n.label=`${o.customer} · ${labels[o.state]||o.state}`;return n;}));}
function renderHome(){const d=state.desk;$('business-date').textContent='Business date · '+d.business_date;$('audit-date').textContent='Today’s approvals · '+d.audit_date_utc+' UTC';$('stats').replaceChildren();[['Pending requests',d.stats.pending,'Ready to review','↗'],['Needs clarification',d.stats.clarification,'Details to resolve','?'],['Allocated today',d.stats.allocated_today,'Distinct orders approved today','✓'],['Lapsed orders',d.stats.lapsed,'Closed without further allocation','◷']].forEach(([label,value,sub,icon])=>{const n=el('div',null,'stat'),h=el('div',label,'stat-label');h.append(el('span',icon,'stat-icon'));n.append(h,el('strong',num(value,0)),el('p',sub,'small'));$('stats').append(n);});$('recent-allocations').replaceChildren(...(d.recent_allocations?.length?d.recent_allocations.map(r=>{const n=el('article',null,'allocation-update');n.append(el('small',stamp(r.timestamp)),el('p',r.summary),action('View current production →',async()=>{await loadOrder(r.order_id);location.hash='production';}));return n;}):[el('p','No allocation has been approved yet. Choose an order below to get a recommendation.','muted')]));renderInbox();$('workshop-pulse').replaceChildren(...d.workshops.map(w=>{const n=el('div',null,'pulse-item'),top=el('div',null,'pulse-top');top.append(el('strong',w.name),tag(w.status,w.status==='ACTIVE'?'Active':pretty(w.status)));const meta=el('div',null,'pulse-meta');meta.append(el('span',w.workshop_id+' · '+w.makes.join(' / ')),el('span',num(w.queue_days)+' days'));const bar=el('progress');bar.max=Math.max(10,...d.workshops.map(x=>x.queue_days));bar.value=w.queue_days;bar.setAttribute('aria-label',w.name+' queue: '+num(w.queue_days)+' days');n.append(top,meta,bar,el('p',w.orders.length?w.orders.map(o=>o.order_id).join(', '):'No named orders in this desk','pulse-orders'));return n;}));}
function inboxRows(search,status){return (state.desk?.inbox||[]).filter(r=>(!status||r.status===status)&&(!search||[r.order_id,r.customer,r.original_message].join(' ').toLowerCase().includes(search.toLowerCase())));}
function renderInbox(){const rows=inboxRows($('inbox-search').value,$('inbox-filter').value);$('inbox-count').textContent=rows.length;table($('inbox-table'),['Order / customer','Due date','Status',''],rows.slice(0,state.inboxLimit).map(r=>[pair(r.order_id||'Order needed',r.customer||r.original_message||'New request'),r.due_date||'Not provided',tag(r.status),action('View details →',()=>openInbox(r),true)]),state.desk.inbox.length?'No requests match these filters.':'All orders are assigned and no open requests remain.');$('inbox-more').hidden=rows.length<=state.inboxLimit;controls();}
function renderQueue(){const rows=inboxRows($('queue-search').value,'');$('request-list').replaceChildren(...rows.map(r=>{const n=el('button',null,'request-item'+(r.session_id&&r.session_id===state.session?.session_id?' selected':''));n.dataset.mutate='';const top=el('span',null,'request-top');top.append(el('strong',r.order_id||'Order needed'),tag(r.status));n.append(top,el('small',r.customer||r.original_message||'New request'));n.addEventListener('click',()=>openInbox(r).catch(report));return n;}));if(!rows.length)$('request-list').append(el('p',state.desk?.inbox.length?'No matching requests.':'All orders are assigned.','panel-note'));controls();}
async function openInbox(r){if(state.pending||state.busy)return;if(r.session_id){state.busy=true;controls();try{await loadSession(r.session_id);location.hash='recommendations';}finally{state.busy=false;controls();}}else await startRequest(`Allocate ${r.order_id}.`,'min_delay');}
async function loadSession(id,navigate=false){state.session=await api('/api/sessions/'+encodeURIComponent(id));state.savedId=id;persist();renderSession();renderQueue();if(navigate)location.hash='recommendations';}
async function startRequest(message,objective){if(state.busy||state.pending)return;state.pending={kind:'create',url:'/api/sessions',body:{session_id:crypto.randomUUID(),objective},firstMessage:message};persist();await deliver();}
function turn(action,message='',extra={}){if(state.busy||state.pending||!state.session)return Promise.resolve();state.pending={kind:'turn',url:'/api/sessions/'+encodeURIComponent(state.session.session_id)+'/turns',body:{request_id:crypto.randomUUID(),expected_version:state.session.version,action,message},...extra};persist();return deliver();}
function editDraft(changes){if(state.busy||state.pending||!state.session||state.session.state==='CLOSED')return Promise.resolve();state.pending={kind:'turn',url:'/api/sessions/'+encodeURIComponent(state.session.session_id)+'/turns',body:{request_id:crypto.randomUUID(),expected_version:state.session.version,action:'message',changes}};persist();return deliver();}
function renderEditor(){const s=state.session,d=s.draft;$('edit-order').value=d.order_id||'';$('edit-order').readOnly=!!d.order_id;$('edit-objective').value=d.objective||s.objective;$('edit-limit').value=d.num_workshop_allowed||1;$('edit-due').value=d.due_date||'';$('edit-deadline').checked=d.deadline_required;$('use-order-details').checked=false;const workshops=state.desk?.workshops||[];const ids=[...new Set([...workshops.map(w=>w.workshop_id),...d.exclusion,...(d.preferred_workshop?[d.preferred_workshop]:[])])];const name=id=>workshops.find(w=>w.workshop_id===id)?.name||'Unknown workshop';const any=el('option','Any eligible workshop');any.value='';$('edit-preferred').replaceChildren(any,...ids.map(id=>{const n=el('option',id+' · '+name(id));n.value=id;return n;}));$('edit-preferred').value=d.preferred_workshop||'';$('edit-exclusions').replaceChildren(...ids.map(id=>{const label=el('label',null,'checkbox'),input=el('input');input.type='checkbox';input.value=id;input.checked=d.exclusion.includes(id);label.append(input,el('span',id+' · '+name(id)));return label;}));$('update-help').textContent=(s.backend==='deepseek'?'DeepSeek can interpret natural-language additions. Existing requirements are kept unless explicitly changed.':'This request uses '+(s.backend==='llm'?'Gemini intake with short follow-up commands':'offline rules')+'. Try “cheapest”, “use two workshops” or “exclude W3”, or use Edit details.')+' Replace full request clears requirements not restated.';}
function detailChanges(){const s=state.session,d=s.draft,values={order_id:$('edit-order').value.trim().toUpperCase(),objective:$('edit-objective').value,num_workshop_allowed:Number($('edit-limit').value),preferred_workshop:$('edit-preferred').value||null,due_date:$('edit-due').value||null,deadline_required:$('edit-deadline').checked,exclusion:[...$('edit-exclusions').querySelectorAll('input:checked')].map(n=>n.value).sort()};const changes={};for(const [key,value]of Object.entries(values)){if(JSON.stringify(value)!==JSON.stringify(d[key])||['order_id','objective','num_workshop_allowed','preferred_workshop','exclusion','due_date'].includes(key))changes[key]=value;}if($('use-order-details').checked)for(const key of ['customer','product','category','pieces','order_date','due_date'])changes[key]=null;return changes;}
async function deliver(){if(!state.pending||state.busy)return;state.busy=true;controls();notify('Saving request…');let revise=false;try{while(state.pending){const current=state.pending;const response=await fetch(current.url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(current.body)});const data=await response.json();if(response.status===401){showLogin();throw Error('Sign in again, then retry the pending operation.');}if(response.status>=500)throw Error(data.result?.message||data.error||'The server could not save this operation.');state.pending=null;if(current.kind==='create'&&data.session){state.session=data.session;state.savedId=data.session.session_id;state.pending={kind:'turn',url:'/api/sessions/'+encodeURIComponent(data.session.session_id)+'/turns',body:{request_id:crypto.randomUUID(),expected_version:data.session.version,action:'message',message:current.firstMessage}};persist();continue;}persist();if(!response.ok){notify(data.result?.message||data.error||'The request was not accepted.',true);if(state.savedId)await loadSession(state.savedId);break;}if(current.kind==='event'){notify(data.result?.message||data.result?.decision_status||'Production change saved.');await loadOrder(current.body.order_id);}else if(data.session){await loadSession(data.session.session_id);$('message').value='';location.hash='recommendations';notify(data.committed?'Allocation approved and saved.':'Request updated. Read the assistant reply below.');revise=!!current.openRevision;}else notify(data.result?.message||'The request was not accepted.',true);}
await refreshDesk();if(revise){$('revised-message').value=state.session.messages.find(m=>m.role==='user')?.content||'';$('revise-dialog').showModal();$('revised-message').focus();}else if(state.session&&location.hash==='#recommendations')$('recommendation').scrollIntoView({block:'start'});}catch(error){notify(error.message+(state.pending?' Your request is saved locally for a safe retry.':''),true);}finally{state.busy=false;controls();}}
function eta(days){if(typeof days!=='number'||!state.session)return '—';const base=new Date(state.session.as_of_date+'T00:00:00Z');base.setUTCDate(base.getUTCDate()+Math.ceil(days-1e-10));return base.toISOString().slice(0,10);}
function renderSession(){const s=state.session;$('no-session').hidden=!!s;$('session-content').hidden=!s;if(!s)return;const r=s.last_response?.result||{},d=s.draft,o=s.last_response?.trace?.order||state.desk?.orders.find(x=>x.order_id===d.order_id)||{};const committed=!!s.last_response?.committed;
$('review-order').textContent=d.order_id||'Order details needed';$('review-state').replaceWith(Object.assign(tag(s.state,committed?'Allocated':null),{id:'review-state'}));$('session-ref').textContent=`Request ${s.session_id} · Revision ${s.version} · Updated ${stamp(s.updated_at)}`;$('original-message').textContent=s.messages?.find(m=>m.role==='user')?.content||'No message yet.';
facts($('parsed-fields'),[['Customer',o.customer||d.customer],['Product',o.product||d.product],['Remaining pieces',o.pieces!==undefined?num(o.pieces-(o.completed_pieces||0),0):d.pieces],['Due date',o.due_date||d.due_date],['Objective',objectives[d.objective||s.objective]],['Maximum workshops',d.num_workshop_allowed||1],['Excluded workshops',d.exclusion.join(', ')||'None'],['Preferred workshop',d.preferred_workshop||'None'],['Hard deadline',d.deadline_required?'Required':'No']]);
$('objective').value=d.objective||s.objective;$('session-feedback').textContent=committed?'This allocation has been saved. Current progress is available in Production.':s.state==='CLOSED'?'Request closed.':'No allocation is saved until you select Accept allocation.';const questions=r.clarifications||s.blockers.map(code=>({question:pretty(code),help:'Use Edit details below to update the request.'}));$('assistant-reply').textContent=questions.length?'I need to resolve '+questions.length+(questions.length===1?' item':' items')+' before I can recommend an allocation.':r.assistant_reply||r.message||'Choose an order or tell me what to allocate. I will ask for any missing details.';$('clarification-list').replaceChildren(...questions.map(q=>{const n=el('div',null,'clarification');n.append(el('strong',q.question),el('p',q.help));return n;}));$('edit-details').open=!!questions.length;renderEditor();$('messages').replaceChildren(...(s.messages||[]).map(m=>{const p=el('div',null,'chat-message '+m.role);p.append(el('small',(m.role==='user'?'Dispatcher':'Desk')+' · '+stamp(m.created_at)),el('span',m.content));return p;}));
$('winner').textContent=r.recommended_workshop_name||'Waiting for a feasible recommendation';$('recommendation-badge').textContent=committed?'Approved':r.success?'Ready for review':'Needs attention';$('recommendation-badge').className='tag '+(r.success?'good':'warn');metrics($('recommendation-metrics'),r);parts($('parts'),r);$('recommendation-warning').hidden=!(r.warnings||[]).length;$('recommendation-warning').textContent=(r.warnings||[]).map(pretty).join(' ');$('next-request').hidden=!committed;$('accept').hidden=committed;table($('candidates'),['Workshop','ETA / days','Cost units','Defect rate'],(r.candidate_ranking||[]).map(w=>[pair(w.workshop_name,w.workshop_id),pair(eta(w.estimated_days),num(w.estimated_days)+' days'),num(w.estimated_cost),num(w.expected_defect_rate*100)+'%']),'No single-workshop candidates available. Review the eligibility checks or revise the request.');const reasons=[...(r.eligible_workshops||[]).map(id=>[id,'Eligible for consideration']),...Object.entries(r.rejected||{}).map(([id,reason])=>[id,pretty(reason)])];$('eligibility').replaceChildren(...reasons.map(([id,reason])=>{const p=el('div',null,'eligibility-row');p.append(el('strong',id),el('span',reason));return p;}));if(!reasons.length)$('eligibility').append(el('p','Eligibility analysis will appear after the order details are complete.','muted small'));renderDecision();controls();}
function metrics(target,r){target.replaceChildren();[['Estimated completion',r.estimated_delivery_date||'—'],['Total cost units',num(r.estimated_cost)],['Expected defect rate',typeof r.expected_defect_rate==='number'?num(r.expected_defect_rate*100)+'%':'—']].forEach(([label,value])=>{const p=el('div',null,'metric');p.append(el('small',label),el('strong',value));target.append(p);});}
function parts(target,r){table(target,['Workshop','Pieces','Queue + production + pickup','Cost units'],(r.allocation||[]).map(a=>[pair(a.workshop_name,a.workshop_id),num(a.pieces,0),`${num(a.queue_days)} + ${num(a.processing_days)} + ${num(a.transport_days)} days`,num(a.estimated_cost)]),'No allocation proposed yet.');}
function panel(title){const n=el('section',null,'panel'),h=el('div',null,'panel-heading'),b=el('div',null,'panel-body');h.append(el('h2',title));n.append(h,b);return [n,b];}
function reasoning(r,trace){const list=el('ol',null,'reason-list');const objective=r.objective;const definitions={min_delay:'Minimize the completion time of the slowest assigned part.',min_cost:'Minimize the total piece cost.',min_defects:'Minimize the piece-weighted expected defect rate.',hybrid:'Balance 0.6 × completion days + 0.4 × defect percentage. This is a heuristic.'};const lines=[definitions[objective]||'No feasible allocation has been selected.',`Eligibility checks apply workshop status, product capability, exclusions and per-workshop batch limits.`,...((r.allocation||[]).map(a=>`${a.workshop_name}: ${a.pieces} pieces. ${num(a.queue_days)} queue days + ${num(a.processing_days)} production days + ${num(a.transport_days)} pickup days = ${num(a.estimated_days)} days; estimated cost ${num(a.estimated_cost)} units.`)),...(r.estimated_delivery_date?[`Estimated completion: ${r.estimated_delivery_date}. Dates round up to whole calendar days.`, `Recorded reason codes: ${(r.reason_codes||[]).join(', ')}.`]:[]),...(r.warnings||[]).map(pretty)];lines.forEach(text=>list.append(el('li',text)));if(trace?.order)list.append(el('li',`Source order ${trace.order.order_id}, version ${trace.order.version}. Approval rechecks this version and the latest queues.`));return list;}
function renderDecision(){const target=$('decision-content');target.replaceChildren();if(!state.session){target.append(el('p','Select a request on the Recommendations page first.','notice'));controls();return;}const r=state.session.last_response?.result||{};const [summary,body]=panel(state.session.draft.order_id||'Request needs clarification');const m=el('div',null,'metrics');metrics(m,r);const p=el('div',null,'table-wrap');parts(p,r);body.append(el('p',r.recommended_workshop_name||r.message||'No recommendation available.'),m,p);const [evidence,eb]=panel('Decision reasoning');eb.append(reasoning(r,state.session.last_response?.trace));target.append(summary,evidence);const rejected=Object.entries(r.rejected||{});if(rejected.length){const [excluded,b]=panel('Why other workshops were excluded');table(b,['Workshop','Eligibility reason'],rejected.map(([id,v])=>[id,pretty(v)]));target.append(excluded);}controls();}
async function loadHistory(){const q=new URLSearchParams({page:state.page,page_size:15,q:$('history-search').value.trim(),status:$('history-status').value});const data=await api('/api/audit?'+q);table($('history-table'),['Order / request','Decision','Approved by','Recorded',''],data.items.map(r=>[pair(r.order_id||'Order not identified',r.request_id.slice(0,12)),tag(r.status),r.approved?r.approved_by||'Not recorded (legacy)':'—',stamp(r.timestamp),action('View record →',()=>showAudit(r.request_id))]),'No decisions match these filters.');$('history-count').textContent=`${data.total} records · Page ${state.page} of ${Math.max(1,Math.ceil(data.total/15))}`;$('history-prev').disabled=state.page<=1;$('history-next').disabled=state.page*15>=data.total;}
async function showAudit(id){const r=await api('/api/audit/'+encodeURIComponent(id)),target=$('audit-detail');target.replaceChildren();const f=el('div');facts(f,[['Order',r.order_id],['Decision',labels[r.status]||r.status],['Message time',stamp(r.message_time)],['Approved by',r.approved?(r.approved_by||'Not recorded (legacy)'):'Not an approval'],['Approval time',stamp(r.approval_timestamp)],['Recorded by',r.actor||'Not recorded (legacy)']]);target.append(f,el('h3','Original message'),el('blockquote',r.original_message),el('h3','Parsed request'),el('pre',JSON.stringify(r.parsed,null,2)),el('h3','Recommendation'),el('p',r.result.recommended_workshop_name||r.result.message||'No allocation'),reasoning(r.result,r.trace));const details=el('details');details.append(el('summary','Full decision record'),el('pre',JSON.stringify(r,null,2)));target.append(details);$('audit-dialog').showModal();}
async function loadWorkshops(){const q=new URLSearchParams({q:$('workshop-search').value.trim(),status:$('workshop-status').value,category:$('workshop-category').value});const data=await api('/api/workshops?'+q);$('workshop-count').textContent=data.items.length+' workshops';table($('workshops-table'),['Workshop','Status','Capability','Capacity / day','Batch limit','Queue',''],data.items.map(w=>[pair(w.name,w.workshop_id),tag(w.status,w.status==='ACTIVE'?'Active':pretty(w.status)),w.makes.join(' / '),num(w.capacity,0),w.max_batch?num(w.max_batch,0):'No limit',num(w.queue_days)+' days',action('Explore →',()=>showWorkshop(w))]),'No workshops match these filters.');}
function showWorkshop(w){const [p,b]=panel(w.name+' · '+w.workshop_id);facts(b,[['Status',w.status],['Capability',w.makes.join(' / ')],['Daily capacity',num(w.capacity,0)+' pieces'],['Maximum batch',w.max_batch||'No limit'],['Queue',num(w.queue_days)+' days'],['Pickup lead time',w.lead_days+' days'],['Cost per piece',num(w.cost)+' units'],['Expected defects',num(w.defect_rate*100)+'%']]);b.append(el('p',w.notes||'No workshop notes.','notice'),el('h3','Orders in queue'));const t=el('div',null,'table-wrap');table(t,['Order','Remaining pieces',''],w.orders.map(o=>[o.order_id,num(o.remaining_pieces,0),action('View production →',async()=>{await loadOrder(o.order_id);location.hash='production';})]),'No active named orders. Imported baseline workload may still contribute to the queue.');b.append(t);$('workshop-detail').replaceChildren(p);p.scrollIntoView({behavior:'auto',block:'nearest'});}
async function loadOrder(id){state.order=await api('/api/orders/'+encodeURIComponent(id));$('production-order').value=id;const o=state.order;facts($('production-details'),[['Order',o.order_id],['State',labels[o.state]||o.state],['Completed pieces',`${o.completed_pieces} / ${o.pieces}`],['Remaining pieces',o.remaining_pieces],['Version',o.version],['Customer',o.customer]]);const t=el('div',null,'table-wrap');table(t,['Workshop','Allocated','Completed','Remaining'],o.allocations.map(a=>[a.workshop_id,a.pieces,a.completed_pieces,a.pieces-a.completed_pieces]),'No active allocations.');const history=el('details');history.append(el('summary','Production event history'),el('pre',JSON.stringify(o.events,null,2)));$('production-details').append(t,history);$('complete-workshop').replaceChildren(...o.allocations.map(a=>{const n=el('option',`${a.workshop_id} · ${a.pieces-a.completed_pieces} remaining`);n.value=a.workshop_id;return n;}));$('production-form').hidden=false;productionFields();}
function productionFields(){const action=$('event-action').value;$('complete-fields').hidden=action!=='complete';$('reassign-fields').hidden=action!=='reassign';$('complete-pieces').required=action==='complete';$('complete-pieces').disabled=action!=='complete';$('event-policy').textContent={complete:'Enter newly completed pieces, not the cumulative total. Partial completion keeps the remaining allocation active.',cancel:'Release all remaining allocations and return the order to Ready. Completed pieces are preserved.',reassign:'Reassign only unfinished pieces. If no feasible replacement exists, the current allocation is preserved.',lapse:'Terminate the order and release remaining allocations. A lapsed order cannot be allocated again.'}[action];}
async function route(){const page=location.hash.slice(1).split('?')[0]||'home';const selected=['home','recommendations','decision','history','workshops','production'].includes(page)?page:'home';document.querySelectorAll('[data-page]').forEach(n=>n.hidden=n.dataset.page!==selected);document.querySelectorAll('[data-nav]').forEach(n=>{const active=n.dataset.nav===(selected==='decision'?'recommendations':selected);n.classList.toggle('active',active);if(active)n.setAttribute('aria-current','page');else n.removeAttribute('aria-current');});$('page-label').textContent={home:'Overview',recommendations:'Recommendations',decision:'Decision review',history:'Allocation history',workshops:'Workshop explorer',production:'Production'}[selected];if(!state.user?.username)return;if(selected==='history')await loadHistory();if(selected==='workshops')await loadWorkshops();if(selected==='decision')renderDecision();window.scrollTo(0,0);}
$('login-form').addEventListener('submit',async event=>{event.preventDefault();const button=event.submitter;button.disabled=true;try{await api('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:$('username').value.trim(),password:$('password').value})});$('password').value='';$('login-feedback').textContent='';await boot();}catch(e){$('login-feedback').textContent=e.message;}finally{button.disabled=false;}});
$('logout').addEventListener('click',async()=>{try{await api('/api/auth/logout',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});try{localStorage.removeItem(storageKey());}catch{}state.user=null;state.session=null;state.pending=null;state.savedId=null;state.order=null;state.desk=null;$('message').value='';$('new-message').value='';$('revised-message').value='';showLogin();}catch(e){report(e);}});
document.querySelectorAll('[data-action="new"]').forEach(b=>b.addEventListener('click',()=>{$('new-dialog').showModal();$('new-message').focus();}));
document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>$(b.dataset.close).close()));
$('new-request-form').addEventListener('submit',e=>{e.preventDefault();const message=$('new-message').value.trim();if(!message)return;$('new-dialog').close();startRequest(message,$('new-objective').value).catch(report);});
$('message-form').addEventListener('submit',e=>{e.preventDefault();const value=$('message').value.trim();if(value)turn('message',value);else notify('Enter an order ID or request update first.',true);});
$('replace').addEventListener('click',()=>{const value=$('message').value.trim();if(value)turn('replace',value);else notify('Enter the complete request to replace the current constraints.',true);});
$('objective').addEventListener('change',()=>turn('message',{min_delay:'fastest',min_cost:'cheapest',min_defects:'lowest defects',hybrid:'hybrid'}[$('objective').value]));
$('edit-request').addEventListener('click',()=>{$('edit-details').open=true;$('edit-details').scrollIntoView({block:'center'});$('edit-order').focus();});
$('details-form').addEventListener('submit',e=>{e.preventDefault();editDraft(detailChanges());});
['accept','decision-accept'].forEach(id=>$(id).addEventListener('click',()=>{if(canAccept())turn('confirm');}));
$('reject').addEventListener('click',()=>turn('message','Reject recommendation',{openRevision:true}));
$('revise-form').addEventListener('submit',e=>{e.preventDefault();const value=$('revised-message').value.trim();if(!value)return;$('revise-dialog').close();turn('replace',value);});
$('close-session').addEventListener('click',()=>turn('close'));
$('retry').addEventListener('click',deliver);
$('next-request').addEventListener('click',()=>{const r=state.desk?.inbox[0];if(r)openInbox(r).catch(report);else notify('All orders are assigned and no open requests remain.');});
$('refresh').addEventListener('click',()=>refreshDesk().then(()=>notify('Overview updated.')).catch(report));
['inbox-search','inbox-filter'].forEach(id=>$(id).addEventListener(id==='inbox-search'?'input':'change',()=>{state.inboxLimit=10;renderInbox();}));
$('inbox-more').addEventListener('click',()=>{state.inboxLimit+=20;renderInbox();});$('queue-search').addEventListener('input',renderQueue);
$('history-filters').addEventListener('submit',e=>{e.preventDefault();state.page=1;loadHistory().catch(report);});
$('history-prev').addEventListener('click',()=>{state.page--;loadHistory().catch(report);});$('history-next').addEventListener('click',()=>{state.page++;loadHistory().catch(report);});
$('workshop-filters').addEventListener('submit',e=>{e.preventDefault();$('workshop-detail').replaceChildren();loadWorkshops().catch(report);});
$('order-lookup').addEventListener('submit',e=>{e.preventDefault();loadOrder($('production-order').value.trim()).catch(error=>{state.order=null;$('production-form').hidden=true;$('production-details').replaceChildren();report(error);});});
$('production-order').addEventListener('input',()=>{state.order=null;$('production-form').hidden=true;$('production-details').replaceChildren();});
$('event-action').addEventListener('change',productionFields);
$('production-form').addEventListener('submit',e=>{e.preventDefault();if(!state.order||state.pending||state.busy)return;const body={action:$('event-action').value,order_id:state.order.order_id,actor:state.user.username,reason:$('event-reason').value.trim(),expected_version:state.order.version,event_id:crypto.randomUUID()};if(body.action==='complete'){body.workshop_id=$('complete-workshop').value;body.pieces=Number($('complete-pieces').value);}if(body.action==='reassign')Object.assign(body,{objective:$('event-objective').value,max_workshops:Number($('event-max').value),exclusion:$('event-exclude').value.split(',').map(s=>s.trim()).filter(Boolean),preferred_workshop:$('event-preferred').value.trim()||null,deadline_required:$('event-deadline').checked});state.event=body;$('event-confirm-text').textContent=`${pretty(body.action)} · ${body.order_id}${body.pieces?' · '+body.pieces+' newly completed pieces at '+body.workshop_id:''}. Reason: ${body.reason}. Recorded as ${state.user.username}. ${$('event-policy').textContent}`;$('event-dialog').showModal();});
$('event-confirm').addEventListener('click',()=>{if(!state.event||state.busy||state.pending)return;$('event-dialog').close();state.pending={kind:'event',url:'/api/events',body:state.event};persist();deliver();});
window.addEventListener('hashchange',()=>route().catch(report));
initTextSize();
boot().catch(error=>{showLogin();$('login-feedback').textContent=error.message;});
